#### Override this file by adding a setting-custom.yaml in the root folder (next to settings.yaml file)
#### Prefix is used to customize the elements, eg yupee will produce: yupee-alert, yupee-modal, etc
#### Comment out the elements you don't want to be created
'prefix'   : 'joomla'
'elements':
            - 'accordion'
            - 'alert'
            - 'group-buttons'
            - 'collapse'
            - 'dropdown'
            - 'modal'
            - 'popover'
            - 'switcher'
            - 'tab'
            - 'tooltip'

## - 'popover' Use css for this
